<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An email containing the instructions to reset your password has been sent to your email address: {email}' => 'Лист, що містить інструкції з активації Вашого акаунту відправлено на Вашу електронну адресу.',
  'An invitation email was sent to the address {email}' => 'Запрошення було надіслано на {email}',
  'Creation Date' => 'Дата создания',
  'Impossible to send email to the address {email}' => 'Неможливо відправити листа за адресою {email}',
  'The activation email was successfully sent to {email}' => 'Лист з інструкціями по активації акаунту надіслано на {email}',
  'Update External Profile' => 'Оновлення Вашого профілю',
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => 'Був запит на зміну пароля.<br/>Вы не можете авторизуватись на сайті доки не змінете пароль.',
  'Access' => 'Доступ',
  'Account not active' => 'Обліковий запис не активований',
  'Activate the account' => 'Активація облікового запису',
  'An Error Occurred. Please try later.' => 'Помилка. Спробуйте трішечки пізніше',
  'An email was sent with the instructions to activate your account to the address {email}.' => 'Лист з інструкціями по активації Вашого акаунту надіслано на {email}',
  'Approve Registration' => 'Підтвердження реєстрації',
  'Ban User' => 'Забанити користувача',
  'Change Password' => 'Змінити пароль',
  'Confirm Password' => 'Підтвердження паролю',
  'Data Updated Successfully' => 'Дані успішно оновленні',
  'Delete' => 'Видалити',
  'Documentation' => 'Документація',
  'Edit Profile' => 'Змінити пароль',
  'Edit {username}\'s Profile' => 'Змінити профіль {username}',
  'Email' => 'Email',
  'Fields with {*} are required.' => 'Поля відмічені  {*} являються обов\'язковими.',
  'General Info' => 'Основні дані',
  'Group' => 'Група',
  'Group Level' => 'Рівень групи',
  'Group Name' => 'Ім\'я групи',
  'Groups' => 'Групи',
  'Home' => 'Домашня сторінка',
  'Invalid email address' => 'Неправильна адреса email',
  'Invite User' => 'Запросити користувача',
  'Level' => 'Рівень',
  'Login Required' => 'Необхідна авторизація',
  'My Profile' => 'Мій профіль',
  'Name' => 'Ім\'я',
  'Old Password' => 'Старий пароль',
  'Password' => 'Пароль',
  'Password Reset: Answer' => 'Відновлення паролю: Відповідь',
  'Password Reset: Question' => 'Відновлення паролю:  Питання',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Будь ласка, введіть літери на картинці зверху <br/> Букви вводяться без врахування регістру.',
  'Proceed' => 'В процесі',
  'Recovery Mode' => 'Режим відновлення',
  'Register' => 'Реєсстрація',
  'Registration Complete, you can now login.' => 'Реєстрація завершена. Можете авторизуватись.',
  'Registration Complete. You now have to wait for an admin to approve your account.' => 'Реєстрація завершена. Слід дочекатись активації адміністратором ресурсу.',
  'Remember Me' => 'Запам\'ятати мене на цьому комп\'ютері ',
  'Request New Password' => 'Запит нового паролю ',
  'Resend Email' => 'Ще раз відправити лист',
  'Root Tools' => 'Root інструменти',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Рутовый пароль повинен містити мінімум 2 цифри і 2 букви але не менше 5 символів.',
  'Save' => 'Зберегти',
  'Security' => 'Захист',
  'The requested page does not exist.' => 'Запитувана сторінка не знайдена.',
  'This account is not approved yet' => 'Обліковий запис не підтверджено.',
  'Update' => 'Оновити',
  'Update User' => 'Змінити дані користувача',
  'Update User Profile' => 'Змінити профіль',
  'User Invitation' => 'Запрошення',
  'User List' => 'Список користувачів',
  'User Name' => 'Ім\'я користувача',
  'User Registration' => 'Реєстрація користувача',
  'Username' => 'Им\'я користувача',
  'Users' => 'Користувачі',
  'Verification Code' => 'Код підтвердження',
  'We are sorry, but your account is banned' => 'Вибачте, але Ваш акаунт заблоковано',
  'You are not allowed to update other accounts' => 'Ви не можете змінювати інші облікові записи',
  'You didn\'t enter the correct password' => 'Неправильний пароль',
  'profile' => 'профіль',
  'register' => 'реєстрація',
  'the confirmation password doesn\'t match the password' => 'паролі не співпадають',
  'the password must be of at least 5 characters' => 'Пароль повинен бути не менше 5 символів',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Пароль має містити не менше 2 літер і цифр. Бути не менше 5 символів.',
  'the password must contain at least 2 digits, 2 letters and a special character' => 'Пароль має містити не менше 2 літер і цифр. Бути не менше 5 символів.',
  'username must be at least 4 characters and can only be alphanumeric' => 'Ім\'я користувача має містити не менше 4 симовлів',
  '{username}\'s Profile' => 'Профіль користувача {username}',
  'REQUEST_FROM' => 'Прізвище, ім\'я та по батькові у наказовому відмінку  для підставновки у заяву',
  'LOST_PASSWORD' => 'Забули свій пароль?',
  'ENTER_SITE_TITLE' => 'Увійти на сайт:',
  'ENTER_SITE' => 'Увійти',
  'FILL_REG_FORM' => 'Уперше на сайті? Заповніть реєстраційну форму:',
  'ENTER_AS_USER' => 'Увійти через соц. мережі:',
  'ENTER_SOCIAL' => 'Ви можете увійти на сайт як користувач соц. мереж:',
  'AUTH_PLEASE' => 'Авторизуйтесь, будь ласка',
  'AUTH' => 'Авторизація',
  'REGISTER_NEW' => 'Реєстрація',
  'REGISTER' => 'Зареєструватись',
  'PASS_6' => 'Пароль має містити мінімум 6 символів',
  'EMAIL_CONF' => 'На вказаний імейл прийде лист з підтвердженням реєстрації',
  'REG_CAPCHA' => 'Захист від автоматичних реєстрації спамерів',
  'REQUIRED_FILDS' => 'Обов\'язкові поля',
  'OR_EMAIL' => 'або',
  'TYPE_USERNAME' => 'Вкажіть',
  
  
);
